### ISSUE TITLE
Pipenv install hangsup

### ISSUE THREAD

**Issue by Mottoweb** [unmade/cyprety-rental-bot#105]
Pipenv install hangs up on installing dep 15/17

<img width="618" alt="Screenshot 2019-12-24 at 11 30 36 AM" src="https://user-images.githubusercontent.com/5813134/71406464-f8135380-2640-11ea-81c4-478d077b0519.png">

Tried deleting lock file but still no luck

**Comment by unmade** [comment]
@Mottoweb 
Last time I had this problem because of the pipenv cache. 
It is usually one of the following locations:

- `~/Library/Caches/pipenv (macOS)`
- `%LOCALAPPDATA%\pipenv\pipenv\Cache (Windows)`
- `~/.cache/pipenv (other operating systems)`

Try manually deleting the whole cache directory and let me know if this works.


P.S. I'm preparing pull request to switch to regular `pip` - too much troubles with `pipenv`.

**Comment by unmade** [comment]
Please see updated README
